<?php
return array (
  'hand_default.php' => '手动区块默认模板',
  'hand_）default.php' => '手动区块默认模板',
  'list_default.php' => '列表区块默认模板',
  'list_navbar.php' => '导航条',
  'html.php' => '内容区块模板-直接输出、不带标题',
  'html_default.php' => '内容区块默认模板',
  'text_default.php' => '文本区块默认模板',
  'list_default_copy.php' => '列表区块默认模板',
  'list_monitor.php' => '云监控区块',
  'list_image.php' => '图片区块，不含头尾',
  'myfocus_kdui.php' => '横幅大图轮播',
  'myfocus_expo.php' => '新闻中心图片轮播',
  'myfocus_mainslider.php' => '横幅大图轮播',
  'image_mainslider.php' => '横幅大图轮播',
  'list_top.php' => '头条',
  'list_atag.php' => '链接列表',
  'text.php' => '文本区块默认模板',
  'floatads.php' => '漂浮广告',
  'mainslider.php' => '大图轮播',
  'navbar.php' => '导航条',
  'list_images.php' => '图片列表，不含头尾',
  'list_images_y.php' => '图片列表，竖版',
  'list_images_x.php' => '图片列表，横版',
  'html_box.php' => '内容区块模板-带头尾',
);
?>