<?php
return array (
  'zotop' => 
  array (
    'name' => 'titan',
    'version' => '2.5',
    'update' => 'http://www.zotop.com/zotop/update',
  ),
  'database' => 
  array (
    'default' => 
    array (
      'driver' => 'mysql',
      'hostname' => 'localhost',
      'hostport' => '3306',
      'username' => 'root',
      'password' => '123456',
      'database' => 'zotop2',
      'pconnect' => NULL,
      'prefix' => 'zotop_',
    ),
  ),
  'app' => 
  array (
    'system' => 
    array (
      'id' => 'system',
      'name' => '系统',
      'description' => '系统应用，实现系统核心功能',
      'type' => 'core',
      'version' => '2.3',
      'dir' => 'system',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '0',
      'status' => '1',
    ),
    'content' => 
    array (
      'id' => 'content',
      'name' => '内容',
      'description' => '站点内容管理、内置新闻、页面、图库等内容模型',
      'type' => 'module',
      'version' => '2.0',
      'dir' => 'content',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '1',
      'status' => '1',
    ),
    'block' => 
    array (
      'id' => 'block',
      'name' => '区块',
      'description' => '网站内容区块碎片化管理和维护',
      'type' => 'module',
      'version' => '2.0',
      'dir' => 'block',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '2',
      'status' => '1',
    ),
    'member' => 
    array (
      'id' => 'member',
      'name' => '会员',
      'description' => '会员相关功能，允许会员注册，并且可以管理注册会员',
      'type' => 'module',
      'version' => '2.0',
      'dir' => 'member',
      'tables' => 'member',
      'dependencies' => '',
      'author' => 'zotop team',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '3',
      'status' => '1',
    ),
    'shop' => 
    array (
      'id' => 'shop',
      'name' => '商城',
      'description' => '在线商城，可以管理商品',
      'type' => 'module',
      'version' => '1.0',
      'dir' => 'shop',
      'tables' => 'goods,goods_type',
      'dependencies' => '',
      'author' => 'zotop team',
      'email' => 'hankx_chen@qq.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '4',
      'status' => '1',
    ),
    'guestbook' => 
    array (
      'id' => 'guestbook',
      'name' => '留言本',
      'description' => '网站留言，拥有留言、回复等功能',
      'type' => 'module',
      'version' => '2.0',
      'dir' => 'guestbook',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '5',
      'status' => '1',
    ),
    'ueditor' => 
    array (
      'id' => 'ueditor',
      'name' => 'UEditor 1.3.6',
      'description' => 'UEditor是由百度web前端研发部开发所见即所得富文本web编辑器，具有轻量，可定制，注重用户体验等特点，开源基于BSD协议，允许自由使用和修改代码...,详细请访问Ueditor官方网站：http://ueditor.baidu.com',
      'type' => 'plugin',
      'version' => '1.6',
      'dir' => 'ueditor',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'hankx_chen',
      'email' => '',
      'homepage' => 'http://ueditor.baidu.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '6',
      'status' => '1',
    ),
    'area' => 
    array (
      'id' => 'area',
      'name' => '地区',
      'description' => '省、市、县三级城市数据，默认数据采用国标行政区划代码',
      'type' => 'module',
      'version' => '1.1',
      'dir' => 'area',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop team',
      'email' => 'hankx_chen@qq.com',
      'homepage' => 'http://zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '7',
      'status' => '1',
    ),
    'kefu' => 
    array (
      'id' => 'kefu',
      'name' => '在线客服',
      'description' => '支持QQ、阿里旺旺等帐号在线服务，帮助网站访问者更加方便快捷的与您取得联系',
      'type' => 'module',
      'version' => '1.8',
      'dir' => 'kefu',
      'tables' => '',
      'dependencies' => '',
      'author' => 'zotop team',
      'email' => '',
      'homepage' => '',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '8',
      'status' => '1',
    ),
    'developer' => 
    array (
      'id' => 'developer',
      'name' => '开发助手',
      'description' => '应用开发助手，应用开发必备工具',
      'type' => 'module',
      'version' => '3.0',
      'dir' => 'developer',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '9',
      'status' => '1',
    ),
    'database' => 
    array (
      'id' => 'database',
      'name' => '数据库管理',
      'description' => '对数据库简单的管理和操作',
      'type' => 'com',
      'version' => '2.0',
      'dir' => 'database',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '10',
      'status' => '1',
    ),
    'translator' => 
    array (
      'id' => 'translator',
      'name' => '别名翻译',
      'description' => '替换系统默认的别名转换方式，将别名翻译成英文',
      'type' => 'plugin',
      'version' => '1.2',
      'dir' => 'translator',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop team',
      'email' => NULL,
      'homepage' => 'http://www.zotop.com',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '11',
      'status' => '1',
    ),
    'solution' => 
    array (
      'id' => 'solution',
      'name' => '解决方案',
      'description' => '解决方案模型，该应用依赖于内容模块',
      'type' => 'plugin',
      'version' => '1.0',
      'dir' => 'solution',
      'tables' => 'content_model_solution',
      'dependencies' => 'content',
      'author' => 'zotop team',
      'email' => '',
      'homepage' => '',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '12',
      'status' => '1',
    ),
    'case' => 
    array (
      'id' => 'case',
      'name' => '案例',
      'description' => '工程案例模型，该应用依赖于内容模块',
      'type' => 'plugin',
      'version' => '1.0',
      'dir' => 'case',
      'tables' => 'content_model_case',
      'dependencies' => 'content',
      'author' => 'zotop team',
      'email' => '',
      'homepage' => '',
      'installtime' => '0',
      'updatetime' => '0',
      'listorder' => '13',
      'status' => '1',
    ),
    'test' => 
    array (
      'id' => 'test',
      'name' => '单元测试',
      'description' => '用于功能测试,测试各种系统的功能。可以发现程序中出现的错误问题',
      'type' => 'module',
      'version' => '1.0',
      'dir' => 'test',
      'tables' => NULL,
      'dependencies' => NULL,
      'author' => 'zotop.chenlei',
      'email' => 'zotop.chenlei@gmail.com',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '1407386190',
      'updatetime' => '1407386190',
      'listorder' => '14',
      'status' => '0',
    ),
    'sitemap' => 
    array (
      'id' => 'sitemap',
      'name' => '网站地图',
      'description' => '通知搜索引擎网站上哪些文件需要索引、这些文件的最后修订时间、更改频度、文件位置、相对优先索引权，建立索引范围和索引的行为习惯',
      'type' => 'module',
      'version' => '1.0',
      'dir' => 'sitemap',
      'tables' => '',
      'dependencies' => '',
      'author' => 'zotop team',
      'email' => '',
      'homepage' => 'http://www.zotop.com',
      'installtime' => '1407401795',
      'updatetime' => '1407401795',
      'listorder' => '15',
      'status' => '1',
    ),
  ),
  'router' => 
  array (
    'content/list-<id:num>-<page:num>.html' => 'content/list/<id>',
    'content/<c:index|list>-<id:num>.html' => 'content/<c>/<id>',
  ),
  'cookie' => 
  array (
    'expire' => 3600,
    'prefix' => 'zotop_',
    'path' => '/',
    'domain' => '',
  ),
  'session' => 
  array (
    'driver' => '',
    'expire' => 1440,
    'autostart' => true,
    'name' => 'sessionid',
    'path' => '',
    'cache_limiter' => 'private_no_expire',
    'cache_expire' => '30',
    'user_cookie' => true,
  ),
  'system' => 
  array (
    'attachment_audio_exts' => 'mp3',
    'attachment_audio_size' => '20',
    'attachment_file_exts' => 'doc,docx,xls,xlsx,ppt,pptx,pps,pdf,txt,rar,zip',
    'attachment_file_size' => '20',
    'attachment_image_exts' => 'jpg,jpeg,gif,bmp,png',
    'attachment_image_size' => '20',
    'attachment_video_exts' => 'flv,swf,mp4,mpeg,rm,rmvb',
    'attachment_video_size' => '20',
    'cache_driver' => 'file',
    'cache_expire' => '3000',
    'cache_memcache' => '127.0.0.1:11211',
    'closed' => '1',
    'code' => '5326',
    'debug' => '0',
    'description' => '111',
    'image_height' => '600',
    'image_quality' => '95',
    'image_resize' => '1',
    'image_width' => '1200',
    'keywords' => '关于',
    'locale_date' => 'Y-m-d',
    'locale_language' => 'zh-cn',
    'locale_time' => 'H:i',
    'locale_timezone' => '8',
    'log' => '1',
    'login_captcha' => '0',
    'login_locktime' => '30',
    'login_maxfailed' => '10',
    'log_expire' => '7',
    'mail' => '1',
    'mailvalid' => '5001',
    'mail_delimiter' => '1',
    'mail_from' => 'hankx_chen@qq.com',
    'mail_mailer' => '2',
    'mail_sign' => 'zotopcms',
    'mail_smtp_auth' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_password' => 'chanlaye',
    'mail_smtp_port' => '25',
    'mail_smtp_username' => 'hankx_chen',
    'safekey' => 'R82FPjR4SEEmQ7dck6Wk0PHeCr9pRFn2',
    'sendto' => 'hankx_chen@qq.com',
    'siteid' => '1',
    'site_closed' => '0',
    'site_closedreason' => '暂时关闭',
    'site_description' => '天天平安网描述',
    'site_keywords' => '天天平安网关键词',
    'site_name' => '天天平安网',
    'site_theme' => 'default',
    'site_title' => '天天平安网',
    'site_url' => 'http://www.zotop.com',
    'title' => '客服二',
    'upload_dir' => '[YYYY]/[MM]',
    'url_model' => 'pathinfo',
    'url_route' => 'a:1:{s:5:"admin";s:12:"system/login";}',
    'url_suffix' => '',
    'url_var' => 'r',
    'watermark' => '1',
    'watermark_enable' => '1',
    'watermark_height' => '200',
    'watermark_image' => 'watermark.png',
    'watermark_opacity' => '95',
    'watermark_position' => 'bottom right',
    'watermark_quality' => '90',
    'watermark_width' => '300',
  ),
  'site' => 
  array (
    'closed' => '0',
    'closedreason' => '暂时关闭！',
    'description' => '天天平安网描述',
    'keywords' => '天天平安网关键词',
    'name' => '天天平安网',
    'site_closed' => '0',
    'site_closedreason' => '暂时关闭',
    'site_description' => '天天平安网描述',
    'site_keywords' => '天天平安网关键词',
    'site_name' => '天天平安网',
    'site_theme' => 'default',
    'site_title' => '天天平安网',
    'site_url' => 'http://www.zotop.com',
    'theme' => 'default',
    'title' => '天天平安网',
    'url' => 'http://www.zotop.com',
  ),
);
?>