<?php
return array (
  'system' => 
  array (
    'id' => 'system',
    'name' => '系统',
    'description' => '系统应用，实现系统核心功能',
    'type' => 'core',
    'version' => '2.3',
    'dir' => 'system',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop.chenlei',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261371',
    'updatetime' => '1415261371',
    'listorder' => '0',
    'status' => '1',
  ),
  'content' => 
  array (
    'id' => 'content',
    'name' => '内容',
    'description' => '站点内容管理、内置新闻、页面、图库等内容模型',
    'type' => 'module',
    'version' => '2.0',
    'dir' => 'content',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop.chenlei',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261372',
    'updatetime' => '1415261372',
    'listorder' => '1',
    'status' => '1',
  ),
  'block' => 
  array (
    'id' => 'block',
    'name' => '区块',
    'description' => '网站内容区块碎片化管理和维护',
    'type' => 'module',
    'version' => '2.0',
    'dir' => 'block',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop.chenlei',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261372',
    'updatetime' => '1415261372',
    'listorder' => '2',
    'status' => '1',
  ),
  'guestbook' => 
  array (
    'id' => 'guestbook',
    'name' => '留言本',
    'description' => '网站留言，拥有留言、回复等功能',
    'type' => 'module',
    'version' => '2.0',
    'dir' => 'guestbook',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop.chenlei',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261372',
    'updatetime' => '1415261372',
    'listorder' => '3',
    'status' => '1',
  ),
  'ueditor' => 
  array (
    'id' => 'ueditor',
    'name' => 'UEditor 1.4.3',
    'description' => 'UEditor是由百度web前端研发部开发所见即所得富文本web编辑器，具有轻量，可定制，注重用户体验等特点，开源基于BSD协议，允许自由使用和修改代码...,详细请访问Ueditor官方网站：http://ueditor.baidu.com',
    'type' => 'plugin',
    'version' => '1.7',
    'dir' => 'ueditor',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'hankx_chen',
    'email' => '',
    'homepage' => 'http://ueditor.baidu.com',
    'installtime' => '1415261373',
    'updatetime' => '1415261373',
    'listorder' => '4',
    'status' => '1',
  ),
  'area' => 
  array (
    'id' => 'area',
    'name' => '地区',
    'description' => '省、市、县三级城市数据，默认数据采用国标行政区划代码',
    'type' => 'module',
    'version' => '1.1',
    'dir' => 'area',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop team',
    'email' => 'hankx_chen@qq.com',
    'homepage' => 'http://zotop.com',
    'installtime' => '1415261373',
    'updatetime' => '1415261373',
    'listorder' => '5',
    'status' => '1',
  ),
  'case' => 
  array (
    'id' => 'case',
    'name' => '案例',
    'description' => '工程案例模型，该应用依赖于内容模块',
    'type' => 'plugin',
    'version' => '1.0',
    'dir' => 'case',
    'tables' => 'content_model_case',
    'dependencies' => 'content',
    'author' => 'zotop team',
    'email' => '',
    'homepage' => '',
    'installtime' => '1415261374',
    'updatetime' => '1415261374',
    'listorder' => '6',
    'status' => '1',
  ),
  'dbimport' => 
  array (
    'id' => 'dbimport',
    'name' => '数据导入',
    'description' => '导入旧版本数据',
    'type' => 'module',
    'version' => '1.0',
    'dir' => 'dbimport',
    'tables' => 'dbimport',
    'dependencies' => '',
    'author' => '',
    'email' => '',
    'homepage' => '',
    'installtime' => '1415261374',
    'updatetime' => '1415261374',
    'listorder' => '7',
    'status' => '1',
  ),
  'developer' => 
  array (
    'id' => 'developer',
    'name' => '开发助手',
    'description' => '应用开发助手，应用开发必备工具',
    'type' => 'module',
    'version' => '3.0',
    'dir' => 'developer',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop.chenlei',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261374',
    'updatetime' => '1415261374',
    'listorder' => '8',
    'status' => '1',
  ),
  'form' => 
  array (
    'id' => 'form',
    'name' => '自定义表单',
    'description' => '通过自定义表单可以自定义一些常用的功能，如：友情链接、简单的留言板、反馈等',
    'type' => 'module',
    'version' => '1.0',
    'dir' => 'form',
    'tables' => 'form,form_field',
    'dependencies' => '',
    'author' => 'zotop',
    'email' => 'deleloper@zotop.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261375',
    'updatetime' => '1415261375',
    'listorder' => '9',
    'status' => '1',
  ),
  'kefu' => 
  array (
    'id' => 'kefu',
    'name' => '在线客服',
    'description' => '支持QQ、阿里旺旺等帐号在线服务，帮助网站访问者更加方便快捷的与您取得联系',
    'type' => 'module',
    'version' => '1.8',
    'dir' => 'kefu',
    'tables' => 'kefu,kefu',
    'dependencies' => '',
    'author' => 'zotop team',
    'email' => '',
    'homepage' => '',
    'installtime' => '1415261375',
    'updatetime' => '1415261375',
    'listorder' => '10',
    'status' => '1',
  ),
  'member' => 
  array (
    'id' => 'member',
    'name' => '会员',
    'description' => '会员相关功能，允许会员注册，并且可以管理注册会员',
    'type' => 'module',
    'version' => '2.0',
    'dir' => 'member',
    'tables' => 'member',
    'dependencies' => '',
    'author' => 'zotop team',
    'email' => 'zotop.chenlei@gmail.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261375',
    'updatetime' => '1415261375',
    'listorder' => '11',
    'status' => '1',
  ),
  'shop' => 
  array (
    'id' => 'shop',
    'name' => '商城',
    'description' => '在线商城，可以管理商品',
    'type' => 'module',
    'version' => '1.0',
    'dir' => 'shop',
    'tables' => 'shop_goods,shop_category,shop_type,shop_goods_attr,shop_spec,shop_brand',
    'dependencies' => '',
    'author' => 'zotop team',
    'email' => 'hankx_chen@qq.com',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261375',
    'updatetime' => '1415261375',
    'listorder' => '12',
    'status' => '1',
  ),
  'sitemap' => 
  array (
    'id' => 'sitemap',
    'name' => '网站地图',
    'description' => '通知搜索引擎网站上哪些文件需要索引、这些文件的最后修订时间、更改频度、文件位置、相对优先索引权，建立索引范围和索引的行为习惯',
    'type' => 'module',
    'version' => '1.0',
    'dir' => 'sitemap',
    'tables' => '',
    'dependencies' => '',
    'author' => 'zotop team',
    'email' => '',
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261376',
    'updatetime' => '1415261376',
    'listorder' => '13',
    'status' => '1',
  ),
  'solution' => 
  array (
    'id' => 'solution',
    'name' => '解决方案',
    'description' => '解决方案模型，该应用依赖于内容模块',
    'type' => 'plugin',
    'version' => '1.0',
    'dir' => 'solution',
    'tables' => 'content_model_solution',
    'dependencies' => 'content',
    'author' => 'zotop team',
    'email' => '',
    'homepage' => '',
    'installtime' => '1415261376',
    'updatetime' => '1415261376',
    'listorder' => '14',
    'status' => '1',
  ),
  'translator' => 
  array (
    'id' => 'translator',
    'name' => '别名翻译',
    'description' => '替换系统默认的别名转换方式，将别名翻译成英文',
    'type' => 'plugin',
    'version' => '1.3',
    'dir' => 'translator',
    'tables' => NULL,
    'dependencies' => NULL,
    'author' => 'zotop team',
    'email' => NULL,
    'homepage' => 'http://www.zotop.com',
    'installtime' => '1415261376',
    'updatetime' => '1415261376',
    'listorder' => '15',
    'status' => '1',
  ),
);
?>