<?php
return array (
  'attachment.delete' => '1',
  'autokeywords' => '1',
  'autosummary' => '250',
  'autothumb' => '1',
  'autuimage' => '1',
  'autusummary' => '250',
  'category_image_height' => '600',
  'category_image_quality' => '98',
  'category_image_resize' => '2',
  'category_image_width' => '1200',
  'image_height' => '600',
  'image_quality' => '98',
  'image_resize' => '1',
  'image_width' => '680',
  'newflag' => 'createtime',
  'newflag_expires' => '72',
  'siteid' => '1',
  'thumb_height' => '600',
  'thumb_quality' => '98',
  'thumb_resize' => '1',
  'thumb_width' => '680',
);
?>